services:
  client1:
    build: ./client/logis-app
    ports:
      - "5173:5173"
    depends_on:
      - server
  
  client2:
    build: ./client/logis-app
    ports:
      - "5174:5173"
    depends_on:
      - server

  server:
    build: ./server/logis-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/logis
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_REDIS_HOST: redis

  redis:
    image: docker.io/library/redis:7.2.4
    container_name : redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: logis
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
